'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Modules.ComprasProveedor

    Partial Public Class Pedidos

        Protected WithEvents upMain As Global.System.Web.UI.UpdatePanel
        Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
        Protected WithEvents btnNuevoPedido As Global.System.Web.UI.WebControls.Button
        Protected WithEvents txtBuscar As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnLimpiar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvPedidos As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents pnlFormCabecera As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents ddlFormaPago As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents pnlDetalleContenedor As Global.System.Web.UI.WebControls.Panel
        Protected WithEvents lblIdSeleccionado As Global.System.Web.UI.WebControls.Label
        Protected WithEvents btnCerrarDetalle As Global.System.Web.UI.WebControls.Button
        Protected WithEvents hfPedidoActivo As Global.System.Web.UI.WebControls.HiddenField
        Protected WithEvents lblCabeceraCode As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblCabeceraFecha As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblCabeceraFormaPago As Global.System.Web.UI.WebControls.Label
        Protected WithEvents ddlProducto As Global.System.Web.UI.WebControls.DropDownList
        Protected WithEvents txtCantSolicitada As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnAgregarItem As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvDetalles As Global.System.Web.UI.WebControls.GridView
        Protected WithEvents lblTotalDetalle As Global.System.Web.UI.WebControls.Label
        Protected WithEvents btnFinalizarPedido As Global.System.Web.UI.WebControls.Button

    End Class

End Namespace