'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Modules.Cliente

    Partial Public Class DetalleProducto

        '''<summary>
        '''lblBreadcrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBreadcrumb As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProducto As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''imgProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgProducto As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblCategoria control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategoria As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNombre control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNombre As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTipo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTipo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPrecioOriginal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrecioOriginal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPrecioFinal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrecioFinal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBadgePromo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBadgePromo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStock As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMaterial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaterial As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblColor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAlto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlto As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAncho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAncho As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProfundidad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProfundidad As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeso control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeso As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hfCantidad control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfCantidad As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfHipId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfHipId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''btnAgregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlNoEncontrado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNoEncontrado As Global.System.Web.UI.WebControls.Panel
    End Class
End Namespace
