CREATE OR REPLACE PACKAGE PKG_BOD_HISTORIAL_PRECIO_VENTA AS
  PROCEDURE REGISTRAR(p_pro_referencia IN VARCHAR2, p_porcetaje IN NUMBER, p_id OUT NUMBER);
  PROCEDURE LISTAR(p_data OUT SYS_REFCURSOR);
  PROCEDURE LISTAR_TODOS(p_data OUT SYS_REFCURSOR);
END PKG_BOD_HISTORIAL_PRECIO_VENTA;
/
