-- TRIGGER 1: Actualizar total del carrito
CREATE OR REPLACE TRIGGER trg_actualizar_total_carrito
AFTER INSERT OR DELETE ON CLI_DETALLE_CARRITO
DECLARE
BEGIN
    UPDATE CLI_CARRITO c
    SET PRE_TOTAL = (
        SELECT NVL(SUM(hv.HV_PRECIO_FINAL * cd.DETPRE_CANTIDAD), 0)
        FROM CLI_DETALLE_CARRITO cd
        JOIN BOD_HISTORIAL_PRECIO_VENTA hv ON cd.HV_HISTORIAL_PRECIO_VENTA = hv.HV_HISTORIAL_PRECIO_VENTA
        WHERE cd.PRE_CARRITO = c.PRE_CARRITO
    );
END;
/

-- TRIGGER 2: Generar codigo de factura automaticamente
CREATE OR REPLACE TRIGGER trg_generar_codigo_factura
BEFORE INSERT ON FAC_FACTURA_CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.FACLI_CODIGO_FACTURA IS NULL THEN
        :NEW.FACLI_CODIGO_FACTURA := 'FAC-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(:NEW.PRE_PRESUPUESTO, 5, '0');
    END IF;
    IF :NEW.FACLI_FECHA IS NULL THEN
        :NEW.FACLI_FECHA := SYSDATE;
    END IF;
END;
/

-- TRIGGER 3: Limpiar carrito vacio
CREATE OR REPLACE TRIGGER trg_limpiar_carrito_vacio
AFTER DELETE ON CLI_DETALLE_CARRITO
BEGIN
    UPDATE CLI_CARRITO c
    SET PRE_TOTAL = (
        SELECT NVL(SUM(hv.HV_PRECIO_FINAL * cd.DETPRE_CANTIDAD), 0)
        FROM CLI_DETALLE_CARRITO cd
        JOIN BOD_HISTORIAL_PRECIO_VENTA hv ON cd.HV_HISTORIAL_PRECIO_VENTA = hv.HV_HISTORIAL_PRECIO_VENTA
        WHERE cd.PRE_CARRITO = c.PRE_CARRITO
    );
END;
/

CREATE OR REPLACE TRIGGER TRG_ELIMINAR_PRODUCTO_SIN_STOCK
AFTER UPDATE OF STO_DISPONIBLE ON BOD_STOCK
FOR EACH ROW
BEGIN
    IF :NEW.STO_DISPONIBLE = 0 THEN
        DELETE FROM CLI_DETALLE_CARRITO cd
        WHERE cd.HV_HISTORIAL_PRECIO_VENTA IN (
            SELECT hv.HV_HISTORIAL_PRECIO_VENTA
            FROM BOD_HISTORIAL_PRECIO_VENTA hv
            JOIN BOD_HISTORIAL_PRECIO bh ON hv.PRO_REFERENCIA = bh.PRO_REFERENCIA
            WHERE bh.HIP_HISTORIAL_PRECIO = :NEW.HIP_HISTORIAL_PRECIO
        );
    END IF;
END;
/

-- TRIGGER 5: Generar correlativo del carrito automaticamente
CREATE OR REPLACE TRIGGER trg_generar_correlativo_carrito
BEFORE INSERT ON CLI_CARRITO
FOR EACH ROW
BEGIN
    IF :NEW.PRE_CORRELATIVO IS NULL THEN
        :NEW.PRE_CORRELATIVO := 'CAR-' || LPAD(:NEW.PRE_CARRITO, 3, '0');
    END IF;
END;
/