'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MueblesAlpes.Web.Modules.AuthUsuarios

    Partial Public Class LoginEmpleado

        Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        ' TAB CREAR
        Protected WithEvents txtCrearId As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtCrearUsuario As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtCrearPassword As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnCrear As Global.System.Web.UI.WebControls.Button

        ' TAB CAMBIAR PASSWORD
        Protected WithEvents txtPassId As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtNuevoPass As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnActPass As Global.System.Web.UI.WebControls.Button

        ' TAB CAMBIAR USUARIO
        Protected WithEvents txtUsrId As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtNuevoUsr As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnActUsr As Global.System.Web.UI.WebControls.Button

        ' TAB VALIDAR
        Protected WithEvents txtValUsr As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents txtValPass As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents btnValidar As Global.System.Web.UI.WebControls.Button

        ' GRID
        Protected WithEvents gvLogins As Global.System.Web.UI.WebControls.GridView

    End Class

End Namespace