-- 1. ESPECIFICACIONES (SPECS)
@PKG_ADMIN_PERMISOS.pks
@PKG_ADMIN_GRUPO_USUARIO.pks
@PKG_ADMIN_LOGIN_EMPLEADO.pks
@PKG_ADMIN_LOGIN_CLIENTE.pks
@PKG_RH_PUESTO.pks
@PKG_RH_EMPLEADO.pks
@PKG_RH_ASCENSO.pks
@PKG_CLI_CLIENTE.pks

-- 2. CUERPOS (BODIES)
@PKG_ADMIN_PERMISOS.pkb
@PKG_ADMIN_GRUPO_USUARIO.pkb
@PKG_ADMIN_LOGIN_EMPLEADO.pkb
@PKG_ADMIN_LOGIN_CLIENTE.pkb
@PKG_RH_PUESTO.pkb
@PKG_RH_EMPLEADO.pkb
@PKG_RH_ASCENSO.pkb
@PKG_CLI_CLIENTE.pkb
