CREATE OR REPLACE PACKAGE PKG_ADMIN_PERMISOS AS
  PROCEDURE PER_CREAR(
    p_descripcion IN VARCHAR2, 
    p_id OUT NUMBER
    );

  PROCEDURE PER_ACTUALIZAR(
    p_id IN NUMBER, 
    p_descripcion IN VARCHAR2
    );

  PROCEDURE PER_ELIMINAR(
    p_id IN NUMBER
    );

  PROCEDURE PER_LISTAR(
    p_data OUT SYS_REFCURSOR
    );

END PKG_ADMIN_PERMISOS;
/