CREATE OR REPLACE PACKAGE PKG_CP_BOD_PEDIDO AS
    PROCEDURE PED_CREAR(p_codigo IN VARCHAR2, p_forma_pago IN VARCHAR2, p_id OUT NUMBER);
    PROCEDURE PED_AGREGAR_DETALLE(p_ped_id IN NUMBER, p_hip_id IN NUMBER, p_cant_sol IN NUMBER);
    PROCEDURE PED_ELIMINAR(p_id IN NUMBER);
    PROCEDURE PED_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CP_BOD_PEDIDO;
/