CREATE OR REPLACE PACKAGE BODY PKG_CP_FAC_FACTURA_PROV AS
    PROCEDURE FAC_PROV_REGISTRAR(p_orc_key IN VARCHAR2, p_fac_cod IN VARCHAR2) IS
    BEGIN
        INSERT INTO FAC_FACTURA_PROVEEDOR(orc_orden_compra, facpro_codigo_factura, facpro_fecha)
        VALUES (p_orc_key, p_fac_cod, SYSDATE);
    END;

    PROCEDURE FAC_PROV_LISTAR(p_data OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_data FOR SELECT * FROM FAC_FACTURA_PROVEEDOR ORDER BY facpro_fecha DESC; END;
END PKG_CP_FAC_FACTURA_PROV;
/