CREATE OR REPLACE PACKAGE PKG_CP_FAC_FACTURA_PROV AS
    PROCEDURE FAC_PROV_REGISTRAR(p_orc_key IN VARCHAR2, p_fac_cod IN VARCHAR2);
    PROCEDURE FAC_PROV_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CP_FAC_FACTURA_PROV;
/