CREATE OR REPLACE PACKAGE PKG_CP_FAC_FACTURA_PROV AS
    PROCEDURE FAC_PROV_REGISTRAR(p_orc_key IN VARCHAR2, p_fac_cod IN VARCHAR2);
    
    -- Se añade el parámetro de la llave anterior para poder cambiarla
    PROCEDURE FAC_PROV_ACTUALIZAR(p_orc_key_old IN VARCHAR2, p_orc_key_new IN VARCHAR2, p_fac_cod IN VARCHAR2);
    
    PROCEDURE FAC_PROV_ELIMINAR(p_orc_key IN VARCHAR2);
    PROCEDURE FAC_PROV_LISTAR(p_data OUT SYS_REFCURSOR);
    PROCEDURE FAC_PROV_BUSCAR(p_texto IN VARCHAR2, p_data OUT SYS_REFCURSOR);
END PKG_CP_FAC_FACTURA_PROV;
/