CREATE OR REPLACE PACKAGE PKG_CP_BOD_ORDEN_COMPRA AS
    PROCEDURE ORC_CREAR(p_orc_key IN VARCHAR2, p_codigo IN VARCHAR2, p_prov_id IN NUMBER, p_total IN NUMBER);
    PROCEDURE ORC_VINCULAR_PEDIDO(p_orc_key IN VARCHAR2, p_ped_id IN NUMBER, p_mat IN VARCHAR2, p_precio IN NUMBER, p_cant IN NUMBER);
    PROCEDURE ORC_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CP_BOD_ORDEN_COMPRA;
/