CREATE OR REPLACE PACKAGE PKG_CP_BOD_PROVEEDOR AS
    PROCEDURE PROV_CREAR(p_nit IN VARCHAR2, p_nombre IN VARCHAR2, p_avenida IN VARCHAR2, p_zona IN VARCHAR2, p_direccion IN VARCHAR2, p_telefono IN VARCHAR2, p_id OUT NUMBER);
    PROCEDURE PROV_ACTUALIZAR(p_id IN NUMBER, p_nit IN VARCHAR2, p_nombre IN VARCHAR2, p_avenida IN VARCHAR2, p_zona IN VARCHAR2, p_direccion IN VARCHAR2, p_telefono IN VARCHAR2);
    PROCEDURE PROV_ELIMINAR(p_id IN NUMBER);
    PROCEDURE PROV_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CP_BOD_PROVEEDOR;
/