CREATE OR REPLACE PACKAGE PKG_CP_FAC_RECLAMO_PROV AS
    PROCEDURE REC_PROV_CREAR(p_orc_key IN VARCHAR2, p_coment IN VARCHAR2, p_estado IN VARCHAR2, p_id OUT NUMBER);
    PROCEDURE REC_PROV_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CP_FAC_RECLAMO_PROV;
/