-- ============================================================
-- INSTALADOR — Catalogo & Inventario
-- ============================================================

ALTER PACKAGE PKG_BOD_CATEGORIA    COMPILE;
ALTER PACKAGE PKG_BOD_CATEGORIA    COMPILE BODY;

ALTER PACKAGE PKG_BOD_MATERIAL     COMPILE;
ALTER PACKAGE PKG_BOD_MATERIAL     COMPILE BODY;

ALTER PACKAGE PKG_BOD_TIPO         COMPILE;
ALTER PACKAGE PKG_BOD_TIPO         COMPILE BODY;

ALTER PACKAGE PKG_BOD_ALMACEN      COMPILE;
ALTER PACKAGE PKG_BOD_ALMACEN      COMPILE BODY;

ALTER PACKAGE PKG_BOD_NICHO        COMPILE;
ALTER PACKAGE PKG_BOD_NICHO        COMPILE BODY;

ALTER PACKAGE PKG_BOD_NIC_ALM      COMPILE;
ALTER PACKAGE PKG_BOD_NIC_ALM      COMPILE BODY;

ALTER PACKAGE PKG_BOD_PRODUCTO     COMPILE;
ALTER PACKAGE PKG_BOD_PRODUCTO     COMPILE BODY;

ALTER PACKAGE PKG_BOD_HISTORIAL_PRECIO COMPILE;
ALTER PACKAGE PKG_BOD_HISTORIAL_PRECIO COMPILE BODY;

ALTER PACKAGE PKG_BOD_STOCK        COMPILE;
ALTER PACKAGE PKG_BOD_STOCK        COMPILE BODY;

ALTER PACKAGE PKG_PROMO_PROMOCION  COMPILE;
ALTER PACKAGE PKG_PROMO_PROMOCION  COMPILE BODY;

-- Verificar que todos quedaron VALID
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
    'PKG_BOD_CATEGORIA',
    'PKG_BOD_MATERIAL',
    'PKG_BOD_TIPO',
    'PKG_BOD_ALMACEN',
    'PKG_BOD_NICHO',
    'PKG_BOD_NIC_ALM',
    'PKG_BOD_PRODUCTO',
    'PKG_BOD_HISTORIAL_PRECIO',
    'PKG_BOD_STOCK',
    'PKG_PROMO_PROMOCION'
 )
 ORDER BY OBJECT_NAME, OBJECT_TYPE;