 -- =========================
 --PKG_CI_CATALOGOS SPEC
  -- =========================
CREATE OR REPLACE PACKAGE PKG_CI_CATALOGOS AS
  -- CATEGORIA
  PROCEDURE CAT_CREAR(p_descripcion IN VARCHAR2, p_id OUT NUMBER);
  PROCEDURE CAT_ACTUALIZAR(p_id IN NUMBER, p_descripcion IN VARCHAR2);
  PROCEDURE CAT_ELIMINAR(p_id IN NUMBER); -- solo si no tiene TIPOS
  PROCEDURE CAT_LISTAR(p_data OUT SYS_REFCURSOR);
  PROCEDURE CAT_BUSCAR(p_texto IN VARCHAR2, p_data OUT SYS_REFCURSOR);

  -- MATERIAL
  PROCEDURE MAT_CREAR(p_descripcion IN VARCHAR2, p_id OUT NUMBER);
  PROCEDURE MAT_ACTUALIZAR(p_id IN NUMBER, p_descripcion IN VARCHAR2);
  PROCEDURE MAT_ELIMINAR(p_id IN NUMBER); -- solo si no tiene PRODUCTOS
  PROCEDURE MAT_LISTAR(p_data OUT SYS_REFCURSOR);
  PROCEDURE MAT_BUSCAR(p_texto IN VARCHAR2, p_data OUT SYS_REFCURSOR);

  -- TIPO
  PROCEDURE TIP_CREAR(p_descripcion IN VARCHAR2, p_cat_categoria IN NUMBER, p_id OUT NUMBER);
  PROCEDURE TIP_ACTUALIZAR(p_id IN NUMBER, p_descripcion IN VARCHAR2, p_cat_categoria IN NUMBER);
  PROCEDURE TIP_ELIMINAR(p_id IN NUMBER); -- solo si no tiene PRODUCTOS
  PROCEDURE TIP_LISTAR(p_data OUT SYS_REFCURSOR);
  PROCEDURE TIP_LISTAR_POR_CATEGORIA(p_cat_categoria IN NUMBER, p_data OUT SYS_REFCURSOR);

  -- ALMACEN
  PROCEDURE ALM_CREAR(p_nombre IN VARCHAR2, p_pais IN VARCHAR2, p_ubicacion IN VARCHAR2, p_id OUT NUMBER);
  PROCEDURE ALM_ACTUALIZAR(p_id IN NUMBER, p_nombre IN VARCHAR2, p_pais IN VARCHAR2, p_ubicacion IN VARCHAR2);
  PROCEDURE ALM_ELIMINAR(p_id IN NUMBER); -- solo si no está en NIC_ALM
  PROCEDURE ALM_LISTAR(p_data OUT SYS_REFCURSOR);

  -- NICHO
  PROCEDURE NIC_CREAR(p_numero IN VARCHAR2, p_zona IN VARCHAR2, p_caracteristica IN VARCHAR2, p_id OUT NUMBER);
  PROCEDURE NIC_ACTUALIZAR(p_id IN NUMBER, p_numero IN VARCHAR2, p_zona IN VARCHAR2, p_caracteristica IN VARCHAR2);
  PROCEDURE NIC_ELIMINAR(p_id IN NUMBER); -- solo si no está en NIC_ALM ni HISTORIAL_PRECIO
  PROCEDURE NIC_LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_CI_CATALOGOS;
/