CREATE OR REPLACE PACKAGE PKG_BOD_NICHO AS
  PROCEDURE CREAR(p_numero IN VARCHAR2, p_zona IN VARCHAR2, p_caracteristica IN VARCHAR2, p_id OUT NUMBER);
  PROCEDURE ACTUALIZAR(p_id IN NUMBER, p_numero IN VARCHAR2, p_zona IN VARCHAR2, p_caracteristica IN VARCHAR2);
  PROCEDURE ELIMINAR(p_id IN NUMBER); -- solo si no está en NIC_ALM ni HISTORIAL_PRECIO
  PROCEDURE LISTAR(p_data OUT SYS_REFCURSOR);
END PKG_BOD_NICHO;
/