 -- =========================
 --PKG_CI_UBICACION SPEC
  -- =========================
  CREATE OR REPLACE PACKAGE PKG_CI_UBICACION AS
  PROCEDURE NIC_ALM_ASIGNAR(p_nic_nicho IN NUMBER, p_alm_almacen IN NUMBER, p_id OUT NUMBER);
  PROCEDURE NIC_ALM_QUITAR(p_id IN NUMBER);
  PROCEDURE NIC_ALM_LISTAR(p_data OUT SYS_REFCURSOR);
  PROCEDURE NIC_ALM_LISTAR_POR_ALMACEN(p_alm_almacen IN NUMBER, p_data OUT SYS_REFCURSOR);
END PKG_CI_UBICACION;
/