'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Modules.CatalogoInventario

    Partial Public Class Precios

        '''<summary>
        '''pnlMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProducto As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlInfoProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInfoProducto As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblNombreProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNombreProducto As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTipo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTipo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMaterial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaterial As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlAlmacen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAlmacen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlNicho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNicho As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPrecioNicho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPrecioNicho As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPrecioNicho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrecioNicho As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPrecio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrecio As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFechaInicio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFechaInicio As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnRegistrar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRegistrar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlMes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlAnio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAnio As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnFiltrar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvHistorial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvHistorial As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
