'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Modules.CatalogoInventario

    Partial Public Class Stock

        '''<summary>
        '''pnlMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMsg As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hfFromPed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfFromPed As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfPedParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfPedParam As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfHipSemilla control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfHipSemilla As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfDetpeParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfDetpeParam As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfPrecioODP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfPrecioODP As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfCantRecibida control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfCantRecibida As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfCantTotalRecib control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfCantTotalRecib As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfHipAnterior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfHipAnterior As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''pnlAvisoPedido control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAvisoPedido As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlPaso1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaso1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProducto As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlInfoProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInfoProducto As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTipo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTipo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMaterial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaterial As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlPaso2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaso2 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlAlmacen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAlmacen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPaso3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaso3 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlNicho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNicho As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPaso4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaso4 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''hfHipId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfHipId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''pnlPrecioVigente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPrecioVigente As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPrecioVigente control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrecioVigente As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlAvisoPrecio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAvisoPrecio As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlStockActual control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlStockActual As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cardDisponible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cardDisponible As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblDisponible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisponible As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMinimo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMinimo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMaximo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaximo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlSumaInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSumaInfo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSumaInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSumaInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlEntradaMercancia control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEntradaMercancia As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCantEntradaLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCantEntradaLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCantidadEntrada control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCantidadEntrada As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnEntrada control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEntrada As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtDisponible control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDisponible As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinimo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinimo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaximo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnGuardar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlEditarLimites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEditarLimites As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnEditarLimites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEditarLimites As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlCancelarLimites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCancelarLimites As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnCancelarLimites control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelarLimites As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlSinStock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSinStock As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDisponibleNuevoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisponibleNuevoLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDisponibleNuevo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDisponibleNuevo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMinimoNuevo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinimoNuevo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMaximoNuevo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaximoNuevo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnCrearStock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCrearStock As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancelar2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancelar2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtFiltroProducto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFiltroProducto As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlFiltroAlmacen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFiltroAlmacen As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFiltroNicho control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFiltroNicho As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnFiltrar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFiltrar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnLimpiar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLimpiar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblContador control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContador As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gvStock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvStock As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
