'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo pueden causar un comportamiento
'     incorrecto y se perderán si se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MueblesAlpes.Web.Modules.AuthUsuarios.Admin

    Partial Public Class GrupoUsuario

        Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
        Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

        Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox
        Protected WithEvents ddlPermisos As Global.System.Web.UI.WebControls.DropDownList

        Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnNuevo As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvGrupos As Global.System.Web.UI.WebControls.GridView

    End Class

End Namespace