'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Los cambios en este archivo pueden causar un comportamiento
'     incorrecto y se perderán si se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace MueblesAlpes.Web.Modules.AuthUsuarios.Admin

    Partial Public Class Permisos

        Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
        Protected WithEvents hfId As Global.System.Web.UI.WebControls.HiddenField

        ' Checkboxes — declarados como HtmlInputCheckBox
        ' porque en el .aspx usas <input type="checkbox" runat="server" />
        Protected WithEvents chkAdmin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        Protected WithEvents chkRH As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        Protected WithEvents chkFac As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        Protected WithEvents chkCli As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        Protected WithEvents chkBod As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        Protected WithEvents chkPromo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
        Protected WithEvents btnNuevo As Global.System.Web.UI.WebControls.Button
        Protected WithEvents gvPermisos As Global.System.Web.UI.WebControls.GridView

    End Class

End Namespace